package nodes

import (
	"bytes"
	"capyflow/api/models"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

type ClaudeNode struct{}

type ClaudeParams struct {
	Prompt       string  `json:"prompt"`
	APIKey       string  `json:"apiKey"`
	Model        string  `json:"model"`
	Temperature  float64 `json:"temperature"`
	MaxTokens    int     `json:"maxTokens"`
	SystemPrompt string  `json:"systemPrompt"`
}

type ClaudeMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type ClaudeRequest struct {
	Model       string          `json:"model"`
	Messages    []ClaudeMessage `json:"messages"`
	MaxTokens   int             `json:"max_tokens"`
	Temperature float64         `json:"temperature,omitempty"`
	System      string          `json:"system,omitempty"`
}

type ClaudeResponse struct {
	ID      string `json:"id"`
	Type    string `json:"type"`
	Role    string `json:"role"`
	Model   string `json:"model"`
	Content []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"content"`
	StopReason string `json:"stop_reason"`
	Usage      *struct {
		InputTokens  int `json:"input_tokens"`
		OutputTokens int `json:"output_tokens"`
	} `json:"usage,omitempty"`
	Error *struct {
		Type    string `json:"type"`
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

func (n *ClaudeNode) Execute(
	node *models.Node,
	prev map[string]map[string]interface{},
) (map[string]interface{}, error) {

	var params ClaudeParams
	if err := json.Unmarshal([]byte(node.Parameters), &params); err != nil {
		return nil, fmt.Errorf("invalid Claude parameters: %v", err)
	}

	if params.Prompt == "" {
		return nil, fmt.Errorf("prompt is required")
	}

	prompt := interpolateString(params.Prompt, prev)
	apiKey := interpolateString(params.APIKey, prev)

	if apiKey == "" {
		return nil, fmt.Errorf("API key is required: please configure your Anthropic API key in the node parameters")
	}

	if params.Model == "" {
		params.Model = "claude-3-5-sonnet-20241022"
	}

	if params.Temperature < 0 {
		params.Temperature = 0.7
	}
	if params.Temperature > 1.0 {
		params.Temperature = 1.0
	}

	if params.MaxTokens <= 0 {
		params.MaxTokens = 1024
	}
	if params.MaxTokens > 8192 {
		params.MaxTokens = 8192
	}

	claudeReq := ClaudeRequest{
		Model:       params.Model,
		MaxTokens:   params.MaxTokens,
		Temperature: params.Temperature,
		Messages: []ClaudeMessage{
			{
				Role:    "user",
				Content: prompt,
			},
		},
	}

	if params.SystemPrompt != "" {
		systemPrompt := interpolateString(params.SystemPrompt, prev)
		claudeReq.System = systemPrompt
	}

	reqBody, err := json.Marshal(claudeReq)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %v", err)
	}

	req, err := http.NewRequest("POST", "https://api.anthropic.com/v1/messages", bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")

	client := &http.Client{
		Timeout: 60 * time.Second,
	}

	startTime := time.Now()
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to call Anthropic API: %v", err)
	}
	defer resp.Body.Close()

	latency := time.Since(startTime).Milliseconds()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	var claudeResp ClaudeResponse
	if err := json.Unmarshal(respBody, &claudeResp); err != nil {
		return nil, fmt.Errorf("failed to parse Anthropic response: %v", err)
	}

	if claudeResp.Error != nil {
		return nil, fmt.Errorf("Anthropic API error: %s", claudeResp.Error.Message)
	}

	if len(claudeResp.Content) == 0 {
		return nil, fmt.Errorf("no response generated by Claude")
	}

	responseText := claudeResp.Content[0].Text
	stopReason := claudeResp.StopReason

	output := map[string]interface{}{
		"response":   responseText,
		"text":       responseText,
		"stopReason": stopReason,
		"latencyMs":  latency,
		"model":      claudeResp.Model,
	}

	if claudeResp.Usage != nil {
		output["usage"] = map[string]interface{}{
			"inputTokens":  claudeResp.Usage.InputTokens,
			"outputTokens": claudeResp.Usage.OutputTokens,
			"totalTokens":  claudeResp.Usage.InputTokens + claudeResp.Usage.OutputTokens,
		}
	}

	return output, nil
}
