package nodes

import (
	"bytes"
	"capyflow/api/models"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

type GeminiNode struct{}

type GeminiParams struct {
	Prompt      string  `json:"prompt"`
	APIKey      string  `json:"apiKey"`
	Temperature float64 `json:"temperature"`
	MaxTokens   int     `json:"maxTokens"`
	SystemPrompt string `json:"systemPrompt"`
}

type GeminiPart struct {
	Text string `json:"text"`
}

type GeminiContent struct {
	Parts []GeminiPart `json:"parts"`
	Role  string       `json:"role,omitempty"`
}

type GeminiGenerationConfig struct {
	Temperature     float64 `json:"temperature"`
	MaxOutputTokens int     `json:"maxOutputTokens"`
}

type GeminiRequest struct {
	Contents         []GeminiContent        `json:"contents"`
	GenerationConfig GeminiGenerationConfig `json:"generationConfig"`
}

type GeminiResponse struct {
	Candidates []struct {
		Content struct {
			Parts []GeminiPart `json:"parts"`
			Role  string       `json:"role"`
		} `json:"content"`
		FinishReason string `json:"finishReason"`
	} `json:"candidates"`
	UsageMetadata *struct {
		PromptTokenCount     int `json:"promptTokenCount"`
		CandidatesTokenCount int `json:"candidatesTokenCount"`
		TotalTokenCount      int `json:"totalTokenCount"`
	} `json:"usageMetadata,omitempty"`
	Error *struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
		Status  string `json:"status"`
	} `json:"error,omitempty"`
}

func (n *GeminiNode) Execute(
	node *models.Node,
	prev map[string]map[string]interface{},
) (map[string]interface{}, error) {

	var params GeminiParams
	if err := json.Unmarshal([]byte(node.Parameters), &params); err != nil {
		return nil, fmt.Errorf("invalid gemini parameters: %v", err)
	}

	if params.Prompt == "" {
		return nil, fmt.Errorf("prompt is required")
	}

	prompt := interpolateString(params.Prompt, prev)
	apiKey := interpolateString(params.APIKey, prev)

	if apiKey == "" {
		return nil, fmt.Errorf("API key is required: please configure your Gemini API key in the node parameters or provide it via context")
	}

	if params.Temperature <= 0 {
		params.Temperature = 0.7
	}
	if params.Temperature > 2.0 {
		params.Temperature = 2.0
	}

	if params.MaxTokens <= 0 {
		params.MaxTokens = 1024
	}
	if params.MaxTokens > 8192 {
		params.MaxTokens = 8192
	}

	systemPrompt := ""
	if params.SystemPrompt != "" {
		systemPrompt = interpolateString(params.SystemPrompt, prev)
	}

	geminiReq := GeminiRequest{
		Contents: []GeminiContent{},
		GenerationConfig: GeminiGenerationConfig{
			Temperature:     params.Temperature,
			MaxOutputTokens: params.MaxTokens,
		},
	}

	if systemPrompt != "" {
		geminiReq.Contents = append(geminiReq.Contents, GeminiContent{
			Parts: []GeminiPart{{Text: systemPrompt}},
			Role:  "user",
		})
		geminiReq.Contents = append(geminiReq.Contents, GeminiContent{
			Parts: []GeminiPart{{Text: "Understood. I will follow these instructions."}},
			Role:  "model",
		})
	}

	geminiReq.Contents = append(geminiReq.Contents, GeminiContent{
		Parts: []GeminiPart{{Text: prompt}},
		Role:  "user",
	})

	reqBody, err := json.Marshal(geminiReq)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %v", err)
	}

	url := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=%s", apiKey)

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{
		Timeout: 60 * time.Second,
	}

	startTime := time.Now()
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to call Gemini API: %v", err)
	}
	defer resp.Body.Close()

	latency := time.Since(startTime).Milliseconds()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("Gemini API error (status %d): %s", resp.StatusCode, string(respBody))
	}

	var geminiResp GeminiResponse
	if err := json.Unmarshal(respBody, &geminiResp); err != nil {
		return nil, fmt.Errorf("failed to parse Gemini response: %v", err)
	}

	if geminiResp.Error != nil {
		return nil, fmt.Errorf("Gemini API error: %s", geminiResp.Error.Message)
	}

	if len(geminiResp.Candidates) == 0 || len(geminiResp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("no response generated by Gemini")
	}

	responseText := geminiResp.Candidates[0].Content.Parts[0].Text
	finishReason := geminiResp.Candidates[0].FinishReason

	output := map[string]interface{}{
		"response":     responseText,
		"text":         responseText,
		"finishReason": finishReason,
		"latencyMs":    latency,
		"model":        "gemini-1.5-flash",
	}

	if geminiResp.UsageMetadata != nil {
		output["usage"] = map[string]interface{}{
			"promptTokens":     geminiResp.UsageMetadata.PromptTokenCount,
			"completionTokens": geminiResp.UsageMetadata.CandidatesTokenCount,
			"totalTokens":      geminiResp.UsageMetadata.TotalTokenCount,
		}
	}

	return output, nil
}
