package nodes

import (
	"bytes"
	"capyflow/api/models"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

type GPTNode struct{}

type GPTParams struct {
	Prompt       string  `json:"prompt"`
	APIKey       string  `json:"apiKey"`
	Model        string  `json:"model"`
	Temperature  float64 `json:"temperature"`
	MaxTokens    int     `json:"maxTokens"`
	SystemPrompt string  `json:"systemPrompt"`
}

type GPTMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type GPTRequest struct {
	Model       string       `json:"model"`
	Messages    []GPTMessage `json:"messages"`
	Temperature float64      `json:"temperature"`
	MaxTokens   int          `json:"max_tokens,omitempty"`
}

type GPTResponse struct {
	ID      string `json:"id"`
	Object  string `json:"object"`
	Created int64  `json:"created"`
	Model   string `json:"model"`
	Choices []struct {
		Index   int `json:"index"`
		Message struct {
			Role    string `json:"role"`
			Content string `json:"content"`
		} `json:"message"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Usage *struct {
		PromptTokens     int `json:"prompt_tokens"`
		CompletionTokens int `json:"completion_tokens"`
		TotalTokens      int `json:"total_tokens"`
	} `json:"usage,omitempty"`
	Error *struct {
		Message string `json:"message"`
		Type    string `json:"type"`
		Code    string `json:"code"`
	} `json:"error,omitempty"`
}

func (n *GPTNode) Execute(
	node *models.Node,
	prev map[string]map[string]interface{},
) (map[string]interface{}, error) {

	var params GPTParams
	if err := json.Unmarshal([]byte(node.Parameters), &params); err != nil {
		return nil, fmt.Errorf("invalid GPT parameters: %v", err)
	}

	if params.Prompt == "" {
		return nil, fmt.Errorf("prompt is required")
	}

	prompt := interpolateString(params.Prompt, prev)
	apiKey := interpolateString(params.APIKey, prev)

	if apiKey == "" {
		return nil, fmt.Errorf("API key is required: please configure your OpenAI API key in the node parameters")
	}

	if params.Model == "" {
		params.Model = "gpt-4o-mini"
	}

	if params.Temperature < 0 {
		params.Temperature = 0.7
	}
	if params.Temperature > 2.0 {
		params.Temperature = 2.0
	}

	if params.MaxTokens <= 0 {
		params.MaxTokens = 1024
	}
	if params.MaxTokens > 16384 {
		params.MaxTokens = 16384
	}

	messages := []GPTMessage{}

	if params.SystemPrompt != "" {
		systemPrompt := interpolateString(params.SystemPrompt, prev)
		messages = append(messages, GPTMessage{
			Role:    "system",
			Content: systemPrompt,
		})
	}

	messages = append(messages, GPTMessage{
		Role:    "user",
		Content: prompt,
	})

	gptReq := GPTRequest{
		Model:       params.Model,
		Messages:    messages,
		Temperature: params.Temperature,
		MaxTokens:   params.MaxTokens,
	}

	reqBody, err := json.Marshal(gptReq)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %v", err)
	}

	req, err := http.NewRequest("POST", "https://api.openai.com/v1/chat/completions", bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", apiKey))

	client := &http.Client{
		Timeout: 60 * time.Second,
	}

	startTime := time.Now()
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to call OpenAI API: %v", err)
	}
	defer resp.Body.Close()

	latency := time.Since(startTime).Milliseconds()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	var gptResp GPTResponse
	if err := json.Unmarshal(respBody, &gptResp); err != nil {
		return nil, fmt.Errorf("failed to parse OpenAI response: %v", err)
	}

	if gptResp.Error != nil {
		return nil, fmt.Errorf("OpenAI API error: %s", gptResp.Error.Message)
	}

	if len(gptResp.Choices) == 0 {
		return nil, fmt.Errorf("no response generated by GPT")
	}

	responseText := gptResp.Choices[0].Message.Content
	finishReason := gptResp.Choices[0].FinishReason

	output := map[string]interface{}{
		"response":     responseText,
		"text":         responseText,
		"finishReason": finishReason,
		"latencyMs":    latency,
		"model":        gptResp.Model,
	}

	if gptResp.Usage != nil {
		output["usage"] = map[string]interface{}{
			"promptTokens":     gptResp.Usage.PromptTokens,
			"completionTokens": gptResp.Usage.CompletionTokens,
			"totalTokens":      gptResp.Usage.TotalTokens,
		}
	}

	return output, nil
}
