package nodes

import (
	"bytes"
	"capyflow/api/models"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"
)

type GroqNode struct{}

type GroqParams struct {
	Prompt       string  `json:"prompt"`
	Model        string  `json:"model"`
	Temperature  float64 `json:"temperature"`
	MaxTokens    int     `json:"maxTokens"`
	SystemPrompt string  `json:"systemPrompt"`
}

type GroqMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type GroqNodeRequest struct {
	Model       string        `json:"model"`
	Messages    []GroqMessage `json:"messages"`
	Temperature float64       `json:"temperature"`
	MaxTokens   int           `json:"max_tokens,omitempty"`
}

type GroqNodeResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
			Role    string `json:"role"`
		} `json:"message"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Usage *struct {
		PromptTokens     int `json:"prompt_tokens"`
		CompletionTokens int `json:"completion_tokens"`
		TotalTokens      int `json:"total_tokens"`
	} `json:"usage,omitempty"`
	Error *struct {
		Message string `json:"message"`
		Type    string `json:"type"`
	} `json:"error,omitempty"`
}

func (n *GroqNode) Execute(
	node *models.Node,
	prev map[string]map[string]interface{},
) (map[string]interface{}, error) {

	var params GroqParams
	if err := json.Unmarshal([]byte(node.Parameters), &params); err != nil {
		return nil, fmt.Errorf("invalid groq parameters: %v", err)
	}

	if params.Prompt == "" {
		return nil, fmt.Errorf("prompt is required")
	}

	// Get API key from environment
	apiKey := os.Getenv("GROQ_API_KEY")
	if apiKey == "" {
		return nil, fmt.Errorf("GROQ_API_KEY not configured in environment")
	}

	prompt := interpolateString(params.Prompt, prev)

	// Default model
	if params.Model == "" {
		params.Model = "llama-3.3-70b-versatile"
	}

	// Temperature validation
	if params.Temperature <= 0 {
		params.Temperature = 0.7
	}
	if params.Temperature > 2.0 {
		params.Temperature = 2.0
	}

	// Max tokens validation
	if params.MaxTokens <= 0 {
		params.MaxTokens = 1024
	}
	if params.MaxTokens > 32768 {
		params.MaxTokens = 32768
	}

	// Build messages
	messages := []GroqMessage{}

	// Always enforce English responses via system message
	baseSystemPrompt := "You are an AI assistant. Always respond in English."
	if params.SystemPrompt != "" {
		systemPrompt := interpolateString(params.SystemPrompt, prev)
		baseSystemPrompt = baseSystemPrompt + "\n\n" + systemPrompt
	}
	messages = append(messages, GroqMessage{
		Role:    "system",
		Content: baseSystemPrompt,
	})

	// Add user prompt
	messages = append(messages, GroqMessage{
		Role:    "user",
		Content: prompt,
	})

	// Create request
	groqReq := GroqNodeRequest{
		Model:       params.Model,
		Messages:    messages,
		Temperature: params.Temperature,
		MaxTokens:   params.MaxTokens,
	}

	reqBody, err := json.Marshal(groqReq)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %v", err)
	}

	url := "https://api.groq.com/openai/v1/chat/completions"
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)

	client := &http.Client{
		Timeout: 60 * time.Second,
	}

	startTime := time.Now()
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to call Groq API: %v", err)
	}
	defer resp.Body.Close()

	latency := time.Since(startTime).Milliseconds()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("Groq API error (status %d): %s", resp.StatusCode, string(respBody))
	}

	var groqResp GroqNodeResponse
	if err := json.Unmarshal(respBody, &groqResp); err != nil {
		return nil, fmt.Errorf("failed to parse Groq response: %v", err)
	}

	if groqResp.Error != nil {
		return nil, fmt.Errorf("Groq API error: %s", groqResp.Error.Message)
	}

	if len(groqResp.Choices) == 0 {
		return nil, fmt.Errorf("no response generated by Groq")
	}

	responseText := groqResp.Choices[0].Message.Content
	finishReason := groqResp.Choices[0].FinishReason

	output := map[string]interface{}{
		"response":     responseText,
		"text":         responseText,
		"finishReason": finishReason,
		"latencyMs":    latency,
		"model":        params.Model,
	}

	if groqResp.Usage != nil {
		output["usage"] = map[string]interface{}{
			"promptTokens":     groqResp.Usage.PromptTokens,
			"completionTokens": groqResp.Usage.CompletionTokens,
			"totalTokens":      groqResp.Usage.TotalTokens,
		}
	}

	return output, nil
}
