package nodes

var Registry = map[string]NodeHandler{
	"manual-trigger":   &ManualTriggerNode{},
	"cron-trigger":     &CronTriggerNode{},
	"telegram-trigger": &TelegramTriggerNode{},
	"set-data":         &SetDataNode{},
	"log":              &LogNode{},
	"if-condition":     &IfConditionNode{},
	"http-request":     &HttpRequestNode{},
	"json-parser":      &JsonParserNode{},
	"webhook-trigger":  &WebhookTriggerNode{},
	"transform-data":   &TransformDataNode{},
	"loop":             &LoopNode{},
	"delay":            &DelayNode{},
	"groq":             &GroqNode{},
	"filter":           &FilterNode{},
	"split":            &SplitNode{},
	"merge":            &MergeNode{},
	"function":         &FunctionNode{},
	"sort":             &SortNode{},
	"csv-parser":       &CSVParserNode{},
	"regex-extract":    &RegexExtractNode{},
	"switch":           &SwitchNode{},
	"error-handler":    &ErrorHandlerNode{},
	"stop":             &StopNode{},
	"email":            &EmailNode{},
	"telegram":         &TelegramNode{},
	"database":         &DatabaseNode{},
	"ai-configurator":  &AIConfiguratorNode{},
	"document-ingest":  &DocumentIngestNode{},
	"ocr-extract":      &OCRExtractNode{},
	"finance-extract":  &FinanceExtractNode{},
}
