package database

import (
	"capyflow/api/models"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func SeedNodeTypes(db *gorm.DB) {
	nodeTypes := []models.NodeType{
		// ===== TRIGGER NODES =====
		{
			ID:             uuid.New().String(),
			Name:           "Manual Trigger",
			Type:           "manual-trigger",
			Category:       models.CategoryTrigger,
			Description:    "Inicia el workflow manualmente con un botón",
			Icon:           "IconPlayerPlay",
			Color:          "#10B981",
			Version:        "1.0.0",
			DefaultInputs:  "[]",
			DefaultOutputs: `[{"id":"output","name":"Output","type":"any"}]`,
			DefaultParams:  "[]",
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Schedule Trigger",
			Type:           "schedule-trigger",
			Category:       models.CategoryTrigger,
			Description:    "Ejecuta el workflow en intervalos programados (cron)",
			Icon:           "IconClock",
			Color:          "#10B981",
			Version:        "1.0.0",
			DefaultInputs:  "[]",
			DefaultOutputs: `[{"id":"output","name":"Output","type":"any"}]`,
			DefaultParams:  `[{"id":"schedule","name":"Schedule","type":"string","required":true,"placeholder":"*/5 * * * *","description":"Expresión cron"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Webhook Trigger",
			Type:           "webhook-trigger",
			Category:       models.CategoryTrigger,
			Description:    "Se activa con peticiones HTTP externas",
			Icon:           "IconWebhook",
			Color:          "#10B981",
			Version:        "1.0.0",
			DefaultInputs:  "[]",
			DefaultOutputs: `[{"id":"body","name":"Body","type":"object"},{"id":"headers","name":"Headers","type":"object"}]`,
			DefaultParams:  `[{"id":"method","name":"Method","type":"select","options":["GET","POST","PUT","DELETE"],"value":"POST"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== AI NODES =====
		{
			ID:             uuid.New().String(),
			Name:           "GPT Node",
			Type:           "gpt-node",
			Category:       models.CategoryAI,
			Description:    "OpenAI GPT-4, GPT-4o para procesamiento de lenguaje natural",
			Icon:           "IconBrain",
			Color:          "#8B5CF6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"prompt","name":"Prompt","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"response","name":"Response","type":"string"},{"id":"tokens","name":"Tokens Used","type":"number"}]`,
			DefaultParams:  `[{"id":"model","name":"Model","type":"select","options":["gpt-4","gpt-4o","gpt-3.5-turbo"],"value":"gpt-4"},{"id":"temperature","name":"Temperature","type":"number","value":0.7},{"id":"maxTokens","name":"Max Tokens","type":"number","value":1000}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Claude Node",
			Type:           "claude-node",
			Category:       models.CategoryAI,
			Description:    "Anthropic Claude (Sonnet, Opus) para IA conversacional",
			Icon:           "IconRobot",
			Color:          "#8B5CF6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"prompt","name":"Prompt","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"response","name":"Response","type":"string"}]`,
			DefaultParams:  `[{"id":"model","name":"Model","type":"select","options":["claude-3-opus","claude-3-sonnet","claude-3-haiku"],"value":"claude-3-sonnet"},{"id":"temperature","name":"Temperature","type":"number","value":0.7}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Image Generation",
			Type:           "image-generation",
			Category:       models.CategoryAI,
			Description:    "Genera imágenes con DALL-E o Stable Diffusion",
			Icon:           "IconPhoto",
			Color:          "#8B5CF6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"prompt","name":"Prompt","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"imageUrl","name":"Image URL","type":"string"},{"id":"image","name":"Image Data","type":"base64"}]`,
			DefaultParams:  `[{"id":"provider","name":"Provider","type":"select","options":["dall-e-3","dall-e-2","stable-diffusion"],"value":"dall-e-3"},{"id":"size","name":"Size","type":"select","options":["1024x1024","1792x1024","1024x1792"],"value":"1024x1024"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Text Summarizer",
			Type:           "text-summarizer",
			Category:       models.CategoryAI,
			Description:    "Resume automáticamente textos largos",
			Icon:           "IconFileText",
			Color:          "#8B5CF6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"text","name":"Text","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"summary","name":"Summary","type":"string"}]`,
			DefaultParams:  `[{"id":"length","name":"Length","type":"select","options":["short","medium","long"],"value":"medium"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== DATA PROCESSING NODES =====
		{
			ID:             uuid.New().String(),
			Name:           "Function Node",
			Type:           "function-node",
			Category:       models.CategoryData,
			Description:    "Ejecuta código JavaScript/Python personalizado",
			Icon:           "IconCode",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input","name":"Input","type":"any"}]`,
			DefaultOutputs: `[{"id":"output","name":"Output","type":"any"}]`,
			DefaultParams:  `[{"id":"code","name":"Code","type":"code","value":"return input;","required":true}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Transform Data",
			Type:           "transform-data",
			Category:       models.CategoryData,
			Description:    "Mapea, filtra y transforma estructuras de datos",
			Icon:           "IconTransform",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"data","name":"Data","type":"any","required":true}]`,
			DefaultOutputs: `[{"id":"result","name":"Result","type":"any"}]`,
			DefaultParams:  `[{"id":"operation","name":"Operation","type":"select","options":["map","filter","reduce"],"value":"map"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "JSON Parser",
			Type:           "json-parser",
			Category:       models.CategoryData,
			Description:    "Parsea y manipula datos JSON",
			Icon:           "IconBraces",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"json","name":"JSON","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"parsed","name":"Parsed","type":"object"}]`,
			DefaultParams:  "[]",
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Merge Data",
			Type:           "merge-data",
			Category:       models.CategoryData,
			Description:    "Combina salidas de múltiples nodos",
			Icon:           "IconGitMerge",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input1","name":"Input 1","type":"any"},{"id":"input2","name":"Input 2","type":"any"}]`,
			DefaultOutputs: `[{"id":"merged","name":"Merged","type":"any"}]`,
			DefaultParams:  "[]",
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== LOGIC NODES =====
		{
			ID:             uuid.New().String(),
			Name:           "Condition (IF)",
			Type:           "condition-if",
			Category:       models.CategoryLogic,
			Description:    "Bifurca el flujo según una condición",
			Icon:           "IconGitBranch",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input","name":"Input","type":"any","required":true}]`,
			DefaultOutputs: `[{"id":"true","name":"True","type":"any"},{"id":"false","name":"False","type":"any"}]`,
			DefaultParams:  `[{"id":"condition","name":"Condition","type":"string","required":true,"placeholder":"value > 10"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Switch",
			Type:           "switch",
			Category:       models.CategoryLogic,
			Description:    "Múltiples caminos según valor",
			Icon:           "IconSwitch",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"value","name":"Value","type":"any","required":true}]`,
			DefaultOutputs: `[{"id":"case1","name":"Case 1","type":"any"},{"id":"case2","name":"Case 2","type":"any"},{"id":"default","name":"Default","type":"any"}]`,
			DefaultParams:  `[{"id":"cases","name":"Cases","type":"array","value":[]}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Loop",
			Type:           "loop",
			Category:       models.CategoryLogic,
			Description:    "Itera sobre arrays o rangos de números",
			Icon:           "IconRepeat",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"array","name":"Array","type":"array","required":true}]`,
			DefaultOutputs: `[{"id":"item","name":"Item","type":"any"},{"id":"index","name":"Index","type":"number"}]`,
			DefaultParams:  "[]",
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Delay",
			Type:           "delay",
			Category:       models.CategoryLogic,
			Description:    "Pausa la ejecución por un tiempo determinado",
			Icon:           "IconClockPause",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input","name":"Input","type":"any"}]`,
			DefaultOutputs: `[{"id":"output","name":"Output","type":"any"}]`,
			DefaultParams:  `[{"id":"duration","name":"Duration (ms)","type":"number","value":1000,"required":true}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== IO NODES =====
		{
			ID:             uuid.New().String(),
			Name:           "HTTP Request",
			Type:           "http-request",
			Category:       models.CategoryIO,
			Description:    "Realiza peticiones HTTP a APIs externas",
			Icon:           "IconWorld",
			Color:          "#EC4899",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"url","name":"URL","type":"string","required":true},{"id":"body","name":"Body","type":"object"}]`,
			DefaultOutputs: `[{"id":"response","name":"Response","type":"object"},{"id":"status","name":"Status Code","type":"number"}]`,
			DefaultParams:  `[{"id":"method","name":"Method","type":"select","options":["GET","POST","PUT","DELETE","PATCH"],"value":"GET"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "File Reader",
			Type:           "file-reader",
			Category:       models.CategoryIO,
			Description:    "Lee contenido de archivos (txt, json, csv)",
			Icon:           "IconFileText",
			Color:          "#EC4899",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"path","name":"File Path","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"content","name":"Content","type":"string"},{"id":"metadata","name":"Metadata","type":"object"}]`,
			DefaultParams:  `[{"id":"encoding","name":"Encoding","type":"select","options":["utf-8","base64"],"value":"utf-8"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Database Query",
			Type:           "database-query",
			Category:       models.CategoryIO,
			Description:    "Ejecuta queries SQL en bases de datos",
			Icon:           "IconDatabase",
			Color:          "#EC4899",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"query","name":"Query","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"results","name":"Results","type":"array"}]`,
			DefaultParams:  `[{"id":"connection","name":"Connection String","type":"string","required":true}]`,
			IsActive:       true,
			IsBeta:         true,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
	}

	// Insertar solo si no existen
	for _, nt := range nodeTypes {
		var existing models.NodeType
		if err := db.First(&existing, "type = ?", nt.Type).Error; err != nil {
			// No existe, crear
			db.Create(&nt)
		}
	}
}
