package database

import (
	"capyflow/api/models"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func SeedNodeTypes(db *gorm.DB) {
	nodeTypes := []models.NodeType{

		// ===== TRIGGERS =====
		{
			ID:             uuid.New().String(),
			Name:           "Manual Trigger",
			Type:           "manual-trigger",
			Category:       models.CategoryTrigger,
			Description:    "Starts the workflow manually",
			Icon:           "IconPlayerPlay",
			Color:          "#10B981",
			Version:        "1.0.0",
			DefaultInputs:  "[]",
			DefaultOutputs: `[{"id":"output","name":"Output","type":"any"}]`,
			DefaultParams:  "[]",
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Webhook Trigger",
			Type:           "webhook-trigger",
			Category:       models.CategoryTrigger,
			Description:    "Triggered by external HTTP requests",
			Icon:           "IconWebhook",
			Color:          "#10B981",
			Version:        "1.0.0",
			DefaultInputs:  "[]",
			DefaultOutputs: `[{"id":"body","name":"Body","type":"object"},{"id":"headers","name":"Headers","type":"object"}]`,
			DefaultParams:  `[{"id":"method","name":"Method","type":"select","options":["GET","POST","PUT","DELETE"],"value":"POST"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== AI / LLM =====
		{
			ID:             uuid.New().String(),
			Name:           "Gemini",
			Type:           "gemini",
			Category:       models.CategoryAI,
			Description:    "Interact with Google Gemini to generate text, analysis and intelligent responses",
			Icon:           "IconSparkles",
			Color:          "#06B6D4",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"prompt","name":"Prompt","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"response","name":"Response","type":"string"},{"id":"text","name":"Text","type":"string"},{"id":"usage","name":"Usage","type":"object"}]`,
			DefaultParams:  `[{"id":"apiKey","name":"API Key","type":"password","required":false,"placeholder":"Uses your saved API key if empty"},{"id":"temperature","name":"Temperature","type":"number","value":0.7,"min":0,"max":2,"step":0.1},{"id":"maxTokens","name":"Max Tokens","type":"number","value":1024,"min":1,"max":8192},{"id":"systemPrompt","name":"System Prompt","type":"text","required":false}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "GPT",
			Type:           "gpt",
			Category:       models.CategoryAI,
			Description:    "Use OpenAI GPT-4 for text generation, reasoning and complex tasks",
			Icon:           "IconBrain",
			Color:          "#10A37F",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"prompt","name":"Prompt","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"response","name":"Response","type":"string"},{"id":"text","name":"Text","type":"string"},{"id":"usage","name":"Usage","type":"object"}]`,
			DefaultParams:  `[{"id":"apiKey","name":"API Key","type":"password","required":true},{"id":"model","name":"Model","type":"select","options":["gpt-4o","gpt-4o-mini","gpt-4-turbo","gpt-3.5-turbo"],"value":"gpt-4o-mini"},{"id":"temperature","name":"Temperature","type":"number","value":0.7,"min":0,"max":2,"step":0.1},{"id":"maxTokens","name":"Max Tokens","type":"number","value":1024,"min":1,"max":16384},{"id":"systemPrompt","name":"System Prompt","type":"text","required":false}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Claude",
			Type:           "claude",
			Category:       models.CategoryAI,
			Description:    "Anthropic Claude for deep analysis, writing and reasoning tasks",
			Icon:           "IconRobot",
			Color:          "#D97706",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"prompt","name":"Prompt","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"response","name":"Response","type":"string"},{"id":"text","name":"Text","type":"string"},{"id":"usage","name":"Usage","type":"object"}]`,
			DefaultParams:  `[{"id":"apiKey","name":"API Key","type":"password","required":true},{"id":"model","name":"Model","type":"select","options":["claude-3-5-sonnet-20241022","claude-3-opus-20240229","claude-3-haiku-20240307"],"value":"claude-3-5-sonnet-20241022"},{"id":"temperature","name":"Temperature","type":"number","value":0.7,"min":0,"max":1,"step":0.1},{"id":"maxTokens","name":"Max Tokens","type":"number","value":1024,"min":1,"max":8192},{"id":"systemPrompt","name":"System Prompt","type":"text","required":false}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== DATA =====
		{
			ID:             uuid.New().String(),
			Name:           "Set Data",
			Type:           "set-data",
			Category:       models.CategoryData,
			Description:    "Define or modify values within the flow",
			Icon:           "IconEdit",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input","name":"Input","type":"any"}]`,
			DefaultOutputs: `[{"id":"output","name":"Output","type":"any"}]`,
			DefaultParams:  `[{"id":"values","name":"Values","type":"object","required":true}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Transform Data",
			Type:           "transform-data",
			Category:       models.CategoryData,
			Description:    "Transform data structures",
			Icon:           "IconTransform",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"data","name":"Data","type":"any","required":true}]`,
			DefaultOutputs: `[{"id":"result","name":"Result","type":"any"}]`,
			DefaultParams:  `[{"id":"operation","name":"Operation","type":"select","options":["map","filter"],"value":"map"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "JSON Parser",
			Type:           "json-parser",
			Category:       models.CategoryData,
			Description:    "Parse JSON strings to objects",
			Icon:           "IconBraces",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"json","name":"JSON","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"parsed","name":"Parsed","type":"object"}]`,
			DefaultParams:  "[]",
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Filter",
			Type:           "filter",
			Category:       models.CategoryData,
			Description:    "Filter arrays based on specific conditions",
			Icon:           "IconFilter",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputData","name":"Input Data","type":"array","required":true}]`,
			DefaultOutputs: `[{"id":"filtered","name":"Filtered","type":"array"},{"id":"count","name":"Count","type":"number"}]`,
			DefaultParams:  `[{"id":"mode","name":"Mode","type":"select","options":["keep","remove"],"value":"keep"},{"id":"field","name":"Field","type":"string"},{"id":"operator","name":"Operator","type":"select","options":["equals","notEquals","contains","startsWith","endsWith","greaterThan","lessThan","greaterOrEqual","lessOrEqual","isEmpty","isNotEmpty"],"value":"equals"},{"id":"value","name":"Value","type":"string"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Split",
			Type:           "split",
			Category:       models.CategoryData,
			Description:    "Split arrays into individual elements or batches",
			Icon:           "IconGitBranch",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputData","name":"Input Data","type":"array","required":true}]`,
			DefaultOutputs: `[{"id":"items","name":"Items","type":"array"},{"id":"count","name":"Count","type":"number"}]`,
			DefaultParams:  `[{"id":"mode","name":"Mode","type":"select","options":["items","batches","field"],"value":"items"},{"id":"batchSize","name":"Batch Size","type":"number","value":1,"min":1},{"id":"field","name":"Field","type":"string"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Merge",
			Type:           "merge",
			Category:       models.CategoryData,
			Description:    "Combine multiple inputs into a unified output",
			Icon:           "IconGitMerge",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input1","name":"Input 1","type":"any"},{"id":"input2","name":"Input 2","type":"any"}]`,
			DefaultOutputs: `[{"id":"merged","name":"Merged","type":"any"},{"id":"count","name":"Count","type":"number"}]`,
			DefaultParams:  `[{"id":"mode","name":"Mode","type":"select","options":["append","combine","merge"],"value":"append"},{"id":"input3","name":"Input 3","type":"any"},{"id":"input4","name":"Input 4","type":"any"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Function",
			Type:           "function",
			Category:       models.CategoryData,
			Description:    "Execute custom JavaScript code for complex transformations",
			Icon:           "IconCode",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputData","name":"Input Data","type":"any"}]`,
			DefaultOutputs: `[{"id":"result","name":"Result","type":"any"},{"id":"logs","name":"Logs","type":"array"}]`,
			DefaultParams:  `[{"id":"code","name":"JavaScript Code","type":"code","required":true,"value":"return input;"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Sort",
			Type:           "sort",
			Category:       models.CategoryData,
			Description:    "Sort arrays by field or value (ascending/descending)",
			Icon:           "IconArrowsSort",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputData","name":"Input Array","type":"array","required":true}]`,
			DefaultOutputs: `[{"id":"sorted","name":"Sorted","type":"array"},{"id":"count","name":"Count","type":"number"}]`,
			DefaultParams:  `[{"id":"field","name":"Field","type":"string"},{"id":"order","name":"Order","type":"select","options":["asc","desc"],"value":"asc"},{"id":"type","name":"Type","type":"select","options":["string","number","date"],"value":"string"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "CSV Parser",
			Type:           "csv-parser",
			Category:       models.CategoryData,
			Description:    "Convert between CSV and JSON (parse/stringify)",
			Icon:           "IconTable",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputData","name":"Input Data","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"data","name":"Data","type":"any"},{"id":"count","name":"Count","type":"number"}]`,
			DefaultParams:  `[{"id":"mode","name":"Mode","type":"select","options":["parse","stringify"],"value":"parse"},{"id":"delimiter","name":"Delimiter","type":"string","value":","},{"id":"hasHeader","name":"Has Header","type":"boolean","value":true}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Regex Extract",
			Type:           "regex-extract",
			Category:       models.CategoryData,
			Description:    "Extract data using regular expressions",
			Icon:           "IconRegex",
			Color:          "#3B82F6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputData","name":"Input Text","type":"string","required":true}]`,
			DefaultOutputs: `[{"id":"matches","name":"Matches","type":"array"},{"id":"count","name":"Count","type":"number"}]`,
			DefaultParams:  `[{"id":"pattern","name":"Pattern","type":"string","required":true},{"id":"mode","name":"Mode","type":"select","options":["first","all","groups"],"value":"first"},{"id":"flags","name":"Flags","type":"string","placeholder":"i, m, s"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== LOGIC =====
		{
			ID:             uuid.New().String(),
			Name:           "If Condition",
			Type:           "if-condition",
			Category:       models.CategoryLogic,
			Description:    "Evaluate a condition and branch the flow",
			Icon:           "IconGitBranch",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input","name":"Input","type":"any","required":true}]`,
			DefaultOutputs: `[{"id":"true","name":"True","type":"any"},{"id":"false","name":"False","type":"any"}]`,
			DefaultParams:  `[{"id":"condition","name":"Condition","type":"string","required":true}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Switch",
			Type:           "switch",
			Category:       models.CategoryLogic,
			Description:    "Multiple routing: directs flow based on multiple cases",
			Icon:           "IconSwitch",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputValue","name":"Input Value","type":"any","required":true}]`,
			DefaultOutputs: `[{"id":"output","name":"Matched Output","type":"string"}]`,
			DefaultParams:  `[{"id":"cases","name":"Cases","type":"array","required":true},{"id":"defaultCase","name":"Default Case","type":"string","value":"default"},{"id":"mode","name":"Mode","type":"select","options":["equals","contains"],"value":"equals"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Error Handler",
			Type:           "error-handler",
			Category:       models.CategoryLogic,
			Description:    "Handle errors with automatic retry and fallback",
			Icon:           "IconAlertTriangle",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputData","name":"Input Data","type":"any"}]`,
			DefaultOutputs: `[{"id":"data","name":"Data","type":"any"},{"id":"hasError","name":"Has Error","type":"boolean"}]`,
			DefaultParams:  `[{"id":"maxRetries","name":"Max Retries","type":"number","value":3},{"id":"retryDelay","name":"Retry Delay (ms)","type":"number","value":1000},{"id":"fallbackMode","name":"Fallback Mode","type":"select","options":["ignore","default","stop"],"value":"ignore"},{"id":"defaultValue","name":"Default Value","type":"any"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
		{
			ID:             uuid.New().String(),
			Name:           "Stop",
			Type:           "stop",
			Category:       models.CategoryLogic,
			Description:    "Stop workflow execution conditionally",
			Icon:           "IconPlayerStop",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"inputValue","name":"Input Value","type":"any"}]`,
			DefaultOutputs: `[{"id":"stopped","name":"Stopped","type":"boolean"},{"id":"message","name":"Message","type":"string"}]`,
			DefaultParams:  `[{"id":"condition","name":"Condition","type":"select","options":["always","if-true","if-false","if-error"],"value":"always"},{"id":"stopMessage","name":"Stop Message","type":"string","value":"Workflow stopped"},{"id":"stopCode","name":"Stop Code","type":"select","options":["success","error"],"value":"success"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== IO =====
		{
			ID:             uuid.New().String(),
			Name:           "HTTP Request",
			Type:           "http-request",
			Category:       models.CategoryIO,
			Description:    "Make HTTP requests to external APIs",
			Icon:           "IconWorld",
			Color:          "#EC4899",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"url","name":"URL","type":"string","required":true},{"id":"body","name":"Body","type":"object"}]`,
			DefaultOutputs: `[{"id":"response","name":"Response","type":"object"},{"id":"status","name":"Status Code","type":"number"}]`,
			DefaultParams:  `[{"id":"method","name":"Method","type":"select","options":["GET","POST","PUT","DELETE"],"value":"GET"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		{
			ID:             uuid.New().String(),
			Name:           "Log",
			Type:           "log",
			Category:       models.CategoryIO,
			Description:    "Log flow information for debugging",
			Icon:           "IconTerminal",
			Color:          "#6B7280",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input","name":"Input","type":"any","required":true}]`,
			DefaultOutputs: `[{"id":"output","name":"Output","type":"any"}]`,
			DefaultParams:  `[{"id":"label","name":"Label","type":"string","required":false}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== CONTROL =====
		{
			ID:             uuid.New().String(),
			Name:           "Loop/ForEach",
			Type:           "loop",
			Category:       models.CategoryControl,
			Description:    "Iterate over arrays and apply operations",
			Icon:           "IconRepeat",
			Color:          "#8B5CF6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"array","name":"Array","type":"array","required":true}]`,
			DefaultOutputs: `[{"id":"items","name":"Items","type":"array"},{"id":"count","name":"Count","type":"number"}]`,
			DefaultParams:  `[{"id":"operation","name":"Operation","type":"select","options":["forEach","map","filter"],"value":"forEach"}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		{
			ID:             uuid.New().String(),
			Name:           "Delay/Wait",
			Type:           "delay",
			Category:       models.CategoryControl,
			Description:    "Pause execution for a specified time",
			Icon:           "IconClock",
			Color:          "#F59E0B",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"input","name":"Input","type":"any","required":false}]`,
			DefaultOutputs: `[{"id":"delayed","name":"Delayed","type":"boolean"},{"id":"durationMs","name":"Duration (ms)","type":"number"}]`,
			DefaultParams:  `[{"id":"duration","name":"Duration","type":"number","value":1000,"min":100,"max":300000}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		// ===== INTEGRATION =====
		{
			ID:             uuid.New().String(),
			Name:           "Email",
			Type:           "email",
			Category:       models.CategoryIntegration,
			Description:    "Send emails via SMTP",
			Icon:           "IconMail",
			Color:          "#10B981",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"trigger","name":"Trigger","type":"any","required":false}]`,
			DefaultOutputs: `[{"id":"sent","name":"Sent","type":"boolean"},{"id":"recipients","name":"Recipients","type":"array"}]`,
			DefaultParams:  `[{"id":"to","name":"To","type":"string","required":true},{"id":"subject","name":"Subject","type":"string","required":true},{"id":"body","name":"Body","type":"textarea","required":true},{"id":"from","name":"From","type":"string","required":true},{"id":"smtpHost","name":"SMTP Host","type":"string","required":true},{"id":"smtpPort","name":"SMTP Port","type":"number","value":587},{"id":"smtpUser","name":"SMTP User","type":"string","required":true},{"id":"smtpPassword","name":"SMTP Password","type":"password","required":true}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		{
			ID:             uuid.New().String(),
			Name:           "Telegram",
			Type:           "telegram",
			Category:       models.CategoryIntegration,
			Description:    "Send messages via Telegram Bot API",
			Icon:           "IconBrandTelegram",
			Color:          "#0088CC",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"trigger","name":"Trigger","type":"any","required":false}]`,
			DefaultOutputs: `[{"id":"sent","name":"Sent","type":"boolean"},{"id":"messageId","name":"Message ID","type":"number"}]`,
			DefaultParams:  `[{"id":"botToken","name":"Bot Token","type":"password","required":true},{"id":"chatId","name":"Chat ID","type":"string","required":true},{"id":"message","name":"Message","type":"textarea","required":true},{"id":"parseMode","name":"Parse Mode","type":"select","options":["","Markdown","HTML"],"value":""}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},

		{
			ID:             uuid.New().String(),
			Name:           "Database",
			Type:           "database",
			Category:       models.CategoryIntegration,
			Description:    "Execute SQL queries on PostgreSQL, MySQL, or SQLite databases",
			Icon:           "IconDatabase",
			Color:          "#8B5CF6",
			Version:        "1.0.0",
			DefaultInputs:  `[{"id":"trigger","name":"Trigger","type":"any","required":false}]`,
			DefaultOutputs: `[{"id":"rows","name":"Rows","type":"array"},{"id":"rowCount","name":"Row Count","type":"number"},{"id":"affectedRows","name":"Affected Rows","type":"number"},{"id":"executionTime","name":"Execution Time","type":"number"}]`,
			DefaultParams:  `[{"id":"driver","name":"Driver","type":"select","options":["postgres","mysql","sqlite3"],"value":"postgres","required":true},{"id":"connectionUrl","name":"Connection URL","type":"string","required":true,"placeholder":"postgres://user:pass@localhost:5432/dbname"},{"id":"query","name":"Query","type":"textarea","required":true,"placeholder":"SELECT * FROM users WHERE id = {{userId}}"},{"id":"timeout","name":"Timeout (ms)","type":"number","value":30000},{"id":"maxRetries","name":"Max Retries","type":"number","value":0},{"id":"retryDelay","name":"Retry Delay (ms)","type":"number","value":1000}]`,
			IsActive:       true,
			IsBeta:         false,
			CreatedAt:      time.Now(),
			UpdatedAt:      time.Now(),
		},
	}

	for _, nt := range nodeTypes {
		var existing models.NodeType
		if err := db.First(&existing, "type = ?", nt.Type).Error; err != nil {
			db.Create(&nt)
		}
	}
}
